### ISSUE TITLE
Huawei: persy_init crash -> SegmentNotFound

### ISSUE THREAD

**Issue by duskoo** [Co-Epi/app-android#280]
**Describe the bug**
Couple of seconds after starting, the app crashes. Device is Honor 9X Pro.

**Additional context**
2020-06-26 11:23:13.993 17014-17028/org.coepi.android I/TcnBluetoothService: Did find TCN=w1r/cwYZxKjXizdwaD7bzQ== from device=59:E8:CB:91:65:31 at estimated distance=null
2020-06-26 11:23:13.995 17014-17028/org.coepi.android D/LOGGER: Observed TCN: C35AFF730619C4A8D78B3770683EDBCD
2020-06-26 11:23:13.998 17014-17028/org.coepi.android V/LOGGER: Inserted observed TCN: C35AFF730619C4A8D78B3770683EDBCD
2020-06-26 11:23:13.998 17014-17057/org.coepi.android I/System.out: [CORE] level: 2, message: Recording a TCN "C35AFF730619C4A8D78B3770683EDBCD"
2020-06-26 11:23:14.000 17014-17028/org.coepi.android I/TcnBluetoothService: Enqueued TCN=w1r/cwYZxKjXizdwaD7bzQ== for advertising
2020-06-26 11:23:14.000 17014-17028/org.coepi.android I/TcnBluetoothService: onCharacteristicWriteRequest result=0 device=59:E8:CB:91:65:31 requestId=2 characteristic=android.bluetooth.BluetoothGattCharacteristic@a96f298 preparedWrite=false responseNeeded=true offset=0 value=[B@9bfcaf1
2020-06-26 11:23:14.002 17014-17057/org.coepi.android I/System.out: **[CORE] level: 2, message: Recording TCN result Err(Error(Custom { kind: Other, error: "Segment not found" }))**
2020-06-26 11:23:17.869 17014-17057/org.coepi.android I/System.out: [CORE] level: 2, message: Retrieved reports count: 1
2020-06-26 11:23:17.875 17014-17057/org.coepi.android I/System.out: [CORE] level: 2, message: R Start matching...
2020-06-26 11:23:17.877 17014-17057/org.coepi.android I/System.out: [CORE] level: 2, message: Took 0s to match reports
2020-06-26 11:23:17.878 17014-17057/org.coepi.android I/System.out: [CORE] level: 4, message: **Matching error: (Error(SegmentNotFound))**

[Persy SegmentNotFound Error](https://docs.rs/persy/0.3.3/src/persy/persy.rs.html#594)

**Comment by ivnsch** [comment]
First impression: no idea. In the [complete log](https://coepi.slack.com/files/U010AFCU6HF/F0163JXMJUS/android-crash-03-88.txt?origin_team=TU1R9BU11&origin_channel=D010NTMSJG0#/) you sent, the Persy initalization is successful (otherwise bootstrap would return an error). In the initialization we create the segment:

```
tx.create_segment("tcn")
```

When storing TCNs, we pass this segment:
```
tx.insert_record("tcn", &observed_tcn.as_bytes())?;
```

It seems `SegmentNotFound` is triggered by it being [NONE](https://docs.rs/persy/0.3.3/src/persy/persy.rs.html#290) or [DROPPED](https://docs.rs/persy/0.3.3/src/persy/persy.rs.html#288). Hmm.

**Comment by ivnsch** [comment]
We also have an [instrumented test](https://github.com/Co-Epi/app-backend-rust/blob/master/android/core/core/src/androidTest/java/org/coepi/core/JNIInterfaceBootstrappedTests.kt#L70) that records TCNs, in the Android code app.

**Comment by duskoo** [comment]
With 0.3(90) the app is no longer crashing, but the error is logged:
![Screenshot_20200626_192158_org coepi android](https://user-images.githubusercontent.com/4785666/85884327-c2fbdf80-b7e2-11ea-8817-738cf87351b2.jpg)

**Comment by duskoo** [comment]
Persy init fails due to HWFramework using blacklisted method to check apk signature (?) during installation. HWFramework is specific to Huawei devices, so this problem should not occur on other brands of phones.
The issue was detected on Huawei Honor 9X Pro with Android 9, EMUI 9.1.1

Crash during apk install:
```
2020-06-27 13:11:29.978 4974-5073/org.coepi.android I/LOGGER: Bootstrapping with db path: "/data/user/0/org.coepi.android/databases"
2020-06-27 13:11:29.979 4974-5073/org.coepi.android I/LOGGER: Bootstrapping with db path: "/data/user/0/org.coepi.android/databases"
2020-06-27 13:11:29.979 4974-5073/org.coepi.android D/LOGGER: Persy path Dusko: "/data/user/0/org.coepi.android/databases/db.persy"
2020-06-27 13:11:29.988 4974-4974/org.coepi.android D/AndroidRuntime: Shutting down VM
2020-06-27 13:11:29.988 4974-4974/org.coepi.android W/g.coepi.androi: **Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)**
2020-06-27 13:11:29.988 4974-4974/org.coepi.android E/g.coepi.androi: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
    
    --------- beginning of crash
2020-06-27 13:11:29.990 4974-4974/org.coepi.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.coepi.android, PID: 4974
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.coepi.android/org.coepi.android.MainActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Single:'org.coepi.android.NotReferencedDependenciesActivator']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3401)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3648)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:117)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:74)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)...
```

[Android Restrictions on non-SDK interfaces](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces)
[HWFramework createDisableExceptionQarthFile](https://github.com/dstmath/HWFramework/blob/651a0f96dbee01d9f593a9a2afc5246dc2ea3b0f/Mate20-9.0/src/main/java/com/msic/qarth/PatchStore.java#L179)

[android-crash-03-90-c.txt](https://github.com/Co-Epi/app-android/files/4840511/android-crash-03-90-c.txt)

**Comment by ivnsch** [comment]
What I wonder is why specifically the `prepare` transaction fails (where the segment is created)? The database creation succeeds. Did you confirm that this is what triggers the crash?

We can confirm this, but before spending more time fixing it, I'd consider consider migrating to Sqlite. The performance difference with Persy for the TCNs is unclear and it's not critical anyway. Most of the time is spent with the in-memory matching, not loading or storing the records. With Sqlite we'd have everything in one place and a dependency less to worry about.

**Comment by ivnsch** [comment]
Btw, I inspected your database and confirmed that it doesn't have segments.

```rust
pub fn init_persy<P: AsRef<Path>>(p: P) -> Res<()> {
    let db = Persy::open_or_create_with(p, Config::new(), |db| {
        let mut tx = db.begin()?;
        tx.create_segment("tcn")?;
        tx.create_index::<i64, u128>(CENS_BY_TS, ValueMode::CLUSTER)?;
        tx.prepare_commit()?.commit()?;
        Ok(())
    })?;
    DB.set(db).map_err(|_| DB_ALREADY_INIT)?;
    Ok(())
}
```
Which means that `open_or_create_with` succeeded, but `tx` didn't, leaving it in an invalid state.

**Comment by ivnsch** [comment]
```
Edit: `Couldn't bootstrap core: status: 3, message: Io(Os { code: 11, kind: WouldBlock, message: "Try again" })`
```
This is the [same error](https://github.com/Co-Epi/app-backend-rust/blob/master/android/core/core/src/androidTest/java/org/coepi/core/JNIInterfaceBootstrappedTests.kt#L25) I got in the instrumentation tests when calling bootstrap in quick succession. Here we see that it's called only once. It's unclear atm how it relates to HWFramework.

Edit: Could you comment the initialization of the Sqlite db? Maybe it's conflicting with that (e.g. the `prepare` block runs at the same time as `Connection::open(sqlite_path)`)?
